package org.aquarius.cicada.core.model;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MovieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	long countByExample(MovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int deleteByExample(MovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int insert(Movie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int insertSelective(Movie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	List<Movie> selectByExample(MovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	Movie selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Movie record, @Param("example") MovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int updateByExample(@Param("record") Movie record, @Param("example") MovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int updateByPrimaryKeySelective(Movie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	int updateByPrimaryKey(Movie record);
}