package org.aquarius.cicada.core.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.time.DateUtils;
import org.aquarius.cicada.core.config.MovieConfiguration;
import org.aquarius.cicada.core.util.MovieUtil;
import org.aquarius.util.AssertUtil;

import com.alibaba.fastjson.annotation.JSONField;

public class Movie implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.ID
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.TITLE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.SITE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String site;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.PAGE_URL
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String pageUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.MP4_FILE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String mp4File;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.ACTOR
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String actor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.TAG
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String tag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.PRODUCER
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String producer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.UNI_ID
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String uniId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.UPDATE_TIME
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.IMAGE_URL
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String imageUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.CHANNEL
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String channel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.CATEGORY
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String category;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.PUBLISH_DATE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	@JSONField(format = "yyyy-MM-dd", deserializeUsing = org.aquarius.cicada.core.internal.js.InternalDateCodec.class)
	private Date publishDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.MEMO
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String memo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.DURATION
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	@JSONField(format = "HH:mm:ss", deserializeUsing = org.aquarius.cicada.core.internal.js.InternalDateCodec.class)
	private Date duration;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.NAME
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.DETAILED
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private Boolean detailed;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.ALBUM_COUNT
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private Integer albumCount = 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.SCORE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private Integer score;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column MOVIE.STATE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private Integer state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	private static final long serialVersionUID = 1L;

	// private transient Date lastDownloadUpdateTime;

	private transient Date lastValidTime;

	private transient boolean analysed;

	/**
	 * Some mission use dynamic urls, so we need to validate the time.
	 *
	 * @return
	 */
	public boolean isOutOfValidTime() {
		if (null == this.lastValidTime) {
			return true;
		}

		return this.lastValidTime.getTime() < System.currentTimeMillis();
	}

	/**
	 * @return the analysed
	 */
	public boolean isAnalysed() {
		return this.analysed;
	}

	/**
	 * @param analysed the analysed to set
	 */
	public void setAnalysed(boolean analysed) {
		this.analysed = analysed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.ID
	 *
	 * @return the value of MOVIE.ID
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.ID
	 *
	 * @param id the value for MOVIE.ID
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.TITLE
	 *
	 * @return the value of MOVIE.TITLE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.TITLE
	 *
	 * @param title the value for MOVIE.TITLE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setTitle(String title) {
		if (null != title) {
			this.title = title.trim();
		}

	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.SITE
	 *
	 * @return the value of MOVIE.SITE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getSite() {
		return this.site;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.SITE
	 *
	 * @param site the value for MOVIE.SITE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setSite(String site) {
		this.site = site;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.PAGE_URL
	 *
	 * @return the value of MOVIE.PAGE_URL
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getPageUrl() {
		return this.pageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.PAGE_URL
	 *
	 * @param pageUrl the value for MOVIE.PAGE_URL
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.MP4_FILE
	 *
	 * @return the value of MOVIE.MP4_FILE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getMp4File() {
		return this.mp4File;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.MP4_FILE
	 *
	 * @param mp4File the value for MOVIE.MP4_FILE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setMp4File(String mp4File) {
		this.mp4File = mp4File;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.ACTOR
	 *
	 * @return the value of MOVIE.ACTOR
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getActor() {
		return this.actor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.ACTOR
	 *
	 * @param actor the value for MOVIE.ACTOR
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setActor(String actor) {
		this.actor = MovieUtil.removeDuplication(actor);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.TAG
	 *
	 * @return the value of MOVIE.TAG
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getTag() {
		return this.tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.TAG
	 *
	 * @param tag the value for MOVIE.TAG
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setTag(String tag) {
		this.tag = MovieUtil.removeDuplication(tag);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.PRODUCER
	 *
	 * @return the value of MOVIE.PRODUCER
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getProducer() {
		return this.producer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.PRODUCER
	 *
	 * @param producer the value for MOVIE.PRODUCER
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setProducer(String producer) {
		this.producer = MovieUtil.removeDuplication(producer);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.UNI_ID
	 *
	 * @return the value of MOVIE.UNI_ID
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getUniId() {
		return this.uniId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.UNI_ID
	 *
	 * @param uniId the value for MOVIE.UNI_ID
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setUniId(String uniId) {
		this.uniId = uniId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.UPDATE_TIME
	 *
	 * @return the value of MOVIE.UPDATE_TIME
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.UPDATE_TIME
	 *
	 * @param updateTime the value for MOVIE.UPDATE_TIME
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.IMAGE_URL
	 *
	 * @return the value of MOVIE.IMAGE_URL
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getImageUrl() {
		return this.imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.IMAGE_URL
	 *
	 * @param imageUrl the value for MOVIE.IMAGE_URL
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.CHANNEL
	 *
	 * @return the value of MOVIE.CHANNEL
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getChannel() {
		return this.channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.CHANNEL
	 *
	 * @param channel the value for MOVIE.CHANNEL
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.CATEGORY
	 *
	 * @return the value of MOVIE.CATEGORY
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getCategory() {
		return this.category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.CATEGORY
	 *
	 * @param category the value for MOVIE.CATEGORY
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setCategory(String category) {
		this.category = MovieUtil.removeDuplication(category);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.PUBLISH_DATE
	 *
	 * @return the value of MOVIE.PUBLISH_DATE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Date getPublishDate() {
		return this.publishDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.PUBLISH_DATE
	 *
	 * @param publishDate the value for MOVIE.PUBLISH_DATE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.MEMO
	 *
	 * @return the value of MOVIE.MEMO
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getMemo() {
		return this.memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.MEMO
	 *
	 * @param memo the value for MOVIE.MEMO
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.DURATION
	 *
	 * @return the value of MOVIE.DURATION
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Date getDuration() {
		return this.duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.DURATION
	 *
	 * @param duration the value for MOVIE.DURATION
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setDuration(Date duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.NAME
	 *
	 * @return the value of MOVIE.NAME
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.NAME
	 *
	 * @param name the value for MOVIE.NAME
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.DETAILED
	 *
	 * @return the value of MOVIE.DETAILED
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Boolean getDetailed() {

		if (this.detailed == null) {
			return false;
		} else {
			return this.detailed;
		}
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.DETAILED
	 *
	 * @param detailed the value for MOVIE.DETAILED
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setDetailed(Boolean detailed) {
		this.detailed = detailed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.ALBUM_COUNT
	 *
	 * @return the value of MOVIE.ALBUM_COUNT
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Integer getAlbumCount() {

		if (this.albumCount == null) {
			return 0;
		}

		return this.albumCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.ALBUM_COUNT
	 *
	 * @param albumCount the value for MOVIE.ALBUM_COUNT
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setAlbumCount(Integer albumCount) {
		this.albumCount = albumCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.SCORE
	 *
	 * @return the value of MOVIE.SCORE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Integer getScore() {
		if (this.score == null) {
			return 0;
		}
		return this.score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.SCORE
	 *
	 * @param score the value for MOVIE.SCORE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column MOVIE.STATE
	 *
	 * @return the value of MOVIE.STATE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Integer getState() {

		if (null == this.state) {
			return StateInit;
		}

		return this.state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column MOVIE.STATE
	 *
	 * @param state the value for MOVIE.STATE
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Movie other = (Movie) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getSite() == null ? other.getSite() == null : this.getSite().equals(other.getSite()))
				&& (this.getPageUrl() == null ? other.getPageUrl() == null : this.getPageUrl().equals(other.getPageUrl()))
				&& (this.getMp4File() == null ? other.getMp4File() == null : this.getMp4File().equals(other.getMp4File()))
				&& (this.getActor() == null ? other.getActor() == null : this.getActor().equals(other.getActor()))
				&& (this.getTag() == null ? other.getTag() == null : this.getTag().equals(other.getTag()))
				&& (this.getProducer() == null ? other.getProducer() == null : this.getProducer().equals(other.getProducer()))
				&& (this.getUniId() == null ? other.getUniId() == null : this.getUniId().equals(other.getUniId()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
				&& (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
				&& (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
				&& (this.getPublishDate() == null ? other.getPublishDate() == null : this.getPublishDate().equals(other.getPublishDate()))
				&& (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
				&& (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getDetailed() == null ? other.getDetailed() == null : this.getDetailed().equals(other.getDetailed()))
				&& (this.getAlbumCount() == null ? other.getAlbumCount() == null : this.getAlbumCount().equals(other.getAlbumCount()))
				&& (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
				&& (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 *
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(this.id);
		sb.append(", title=").append(this.title);
		sb.append(", site=").append(this.site);
		sb.append(", pageUrl=").append(this.pageUrl);
		sb.append(", mp4File=").append(this.mp4File);
		sb.append(", actor=").append(this.actor);
		sb.append(", tag=").append(this.tag);
		sb.append(", producer=").append(this.producer);
		sb.append(", uniId=").append(this.uniId);
		sb.append(", updateTime=").append(this.updateTime);
		sb.append(", imageUrl=").append(this.imageUrl);
		sb.append(", channel=").append(this.channel);
		sb.append(", category=").append(this.category);
		sb.append(", publishDate=").append(this.publishDate);
		sb.append(", memo=").append(this.memo);
		sb.append(", duration=").append(this.duration);
		sb.append(", name=").append(this.name);
		sb.append(", detailed=").append(this.detailed);
		sb.append(", albumCount=").append(this.albumCount);
		sb.append(", score=").append(this.score);
		sb.append(", state=").append(this.state);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public static final int StateInit = 1;

	public static final int StateParsed = 2;

	public static final int StateDownloading = 4;

	public static final int StateFinished = 8;

	public static final int StateIgnored = 16;

	public static final int StateError = 32;

	// public static final int StateDeleted = 64;

	public static final int StateDuplicated = 256;

	public static final String PropertyTitle = "title";

	public static final String PropertyPageUrl = "pageUrl";

	public static boolean isSupportDownload(Movie movie) {
		AssertUtil.assertNotNull(movie);

		int state = movie.getState();
		return state == StateInit || state == StateParsed;
	}

	/**
	 *
	 */
	public Movie() {
		super();

		this.state = StateInit;
	}

	private transient List<DownloadInfo> downloadInfoList = new ArrayList<DownloadInfo>();

	private transient boolean includeDownloadInfo = false;

	/**
	 * @return the downloadInfoList
	 */
	public List<DownloadInfo> getDownloadInfoList() {
		return this.downloadInfoList;
	}

	/**
	 * Set the download info.<BR>
	 *
	 * @param downloadInfoList
	 */
	public void setDownloadInfoList(List<DownloadInfo> downloadInfoList, boolean includeDownloadInfo) {
		this.downloadInfoList.clear();
		this.downloadInfoList.addAll(downloadInfoList);

		this.includeDownloadInfo = includeDownloadInfo;
		this.lastValidTime = DateUtils.addMinutes(new Date(), MovieConfiguration.DefaultOutTimeInMinutes);
	}

	/**
	 * @return the includeDownloadInfo
	 */
	public boolean isIncludeDownloadInfo() {
		return this.includeDownloadInfo;
	}

}