package org.aquarius.cicada.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MovieExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public MovieExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andSiteIsNull() {
			addCriterion("SITE is null");
			return (Criteria) this;
		}

		public Criteria andSiteIsNotNull() {
			addCriterion("SITE is not null");
			return (Criteria) this;
		}

		public Criteria andSiteEqualTo(String value) {
			addCriterion("SITE =", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotEqualTo(String value) {
			addCriterion("SITE <>", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThan(String value) {
			addCriterion("SITE >", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThanOrEqualTo(String value) {
			addCriterion("SITE >=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThan(String value) {
			addCriterion("SITE <", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThanOrEqualTo(String value) {
			addCriterion("SITE <=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLike(String value) {
			addCriterion("SITE like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotLike(String value) {
			addCriterion("SITE not like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteIn(List<String> values) {
			addCriterion("SITE in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotIn(List<String> values) {
			addCriterion("SITE not in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteBetween(String value1, String value2) {
			addCriterion("SITE between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotBetween(String value1, String value2) {
			addCriterion("SITE not between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andPageUrlIsNull() {
			addCriterion("PAGE_URL is null");
			return (Criteria) this;
		}

		public Criteria andPageUrlIsNotNull() {
			addCriterion("PAGE_URL is not null");
			return (Criteria) this;
		}

		public Criteria andPageUrlEqualTo(String value) {
			addCriterion("PAGE_URL =", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlNotEqualTo(String value) {
			addCriterion("PAGE_URL <>", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlGreaterThan(String value) {
			addCriterion("PAGE_URL >", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlGreaterThanOrEqualTo(String value) {
			addCriterion("PAGE_URL >=", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlLessThan(String value) {
			addCriterion("PAGE_URL <", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlLessThanOrEqualTo(String value) {
			addCriterion("PAGE_URL <=", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlLike(String value) {
			addCriterion("PAGE_URL like", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlNotLike(String value) {
			addCriterion("PAGE_URL not like", value, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlIn(List<String> values) {
			addCriterion("PAGE_URL in", values, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlNotIn(List<String> values) {
			addCriterion("PAGE_URL not in", values, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlBetween(String value1, String value2) {
			addCriterion("PAGE_URL between", value1, value2, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andPageUrlNotBetween(String value1, String value2) {
			addCriterion("PAGE_URL not between", value1, value2, "pageUrl");
			return (Criteria) this;
		}

		public Criteria andMp4FileIsNull() {
			addCriterion("MP4_FILE is null");
			return (Criteria) this;
		}

		public Criteria andMp4FileIsNotNull() {
			addCriterion("MP4_FILE is not null");
			return (Criteria) this;
		}

		public Criteria andMp4FileEqualTo(String value) {
			addCriterion("MP4_FILE =", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileNotEqualTo(String value) {
			addCriterion("MP4_FILE <>", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileGreaterThan(String value) {
			addCriterion("MP4_FILE >", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileGreaterThanOrEqualTo(String value) {
			addCriterion("MP4_FILE >=", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileLessThan(String value) {
			addCriterion("MP4_FILE <", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileLessThanOrEqualTo(String value) {
			addCriterion("MP4_FILE <=", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileLike(String value) {
			addCriterion("MP4_FILE like", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileNotLike(String value) {
			addCriterion("MP4_FILE not like", value, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileIn(List<String> values) {
			addCriterion("MP4_FILE in", values, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileNotIn(List<String> values) {
			addCriterion("MP4_FILE not in", values, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileBetween(String value1, String value2) {
			addCriterion("MP4_FILE between", value1, value2, "mp4File");
			return (Criteria) this;
		}

		public Criteria andMp4FileNotBetween(String value1, String value2) {
			addCriterion("MP4_FILE not between", value1, value2, "mp4File");
			return (Criteria) this;
		}

		public Criteria andActorIsNull() {
			addCriterion("ACTOR is null");
			return (Criteria) this;
		}

		public Criteria andActorIsNotNull() {
			addCriterion("ACTOR is not null");
			return (Criteria) this;
		}

		public Criteria andActorEqualTo(String value) {
			addCriterion("ACTOR =", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotEqualTo(String value) {
			addCriterion("ACTOR <>", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorGreaterThan(String value) {
			addCriterion("ACTOR >", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorGreaterThanOrEqualTo(String value) {
			addCriterion("ACTOR >=", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorLessThan(String value) {
			addCriterion("ACTOR <", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorLessThanOrEqualTo(String value) {
			addCriterion("ACTOR <=", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorLike(String value) {
			addCriterion("ACTOR like", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotLike(String value) {
			addCriterion("ACTOR not like", value, "actor");
			return (Criteria) this;
		}

		public Criteria andActorIn(List<String> values) {
			addCriterion("ACTOR in", values, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotIn(List<String> values) {
			addCriterion("ACTOR not in", values, "actor");
			return (Criteria) this;
		}

		public Criteria andActorBetween(String value1, String value2) {
			addCriterion("ACTOR between", value1, value2, "actor");
			return (Criteria) this;
		}

		public Criteria andActorNotBetween(String value1, String value2) {
			addCriterion("ACTOR not between", value1, value2, "actor");
			return (Criteria) this;
		}

		public Criteria andTagIsNull() {
			addCriterion("TAG is null");
			return (Criteria) this;
		}

		public Criteria andTagIsNotNull() {
			addCriterion("TAG is not null");
			return (Criteria) this;
		}

		public Criteria andTagEqualTo(String value) {
			addCriterion("TAG =", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotEqualTo(String value) {
			addCriterion("TAG <>", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThan(String value) {
			addCriterion("TAG >", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThanOrEqualTo(String value) {
			addCriterion("TAG >=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThan(String value) {
			addCriterion("TAG <", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThanOrEqualTo(String value) {
			addCriterion("TAG <=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLike(String value) {
			addCriterion("TAG like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotLike(String value) {
			addCriterion("TAG not like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagIn(List<String> values) {
			addCriterion("TAG in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotIn(List<String> values) {
			addCriterion("TAG not in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagBetween(String value1, String value2) {
			addCriterion("TAG between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotBetween(String value1, String value2) {
			addCriterion("TAG not between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andProducerIsNull() {
			addCriterion("PRODUCER is null");
			return (Criteria) this;
		}

		public Criteria andProducerIsNotNull() {
			addCriterion("PRODUCER is not null");
			return (Criteria) this;
		}

		public Criteria andProducerEqualTo(String value) {
			addCriterion("PRODUCER =", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotEqualTo(String value) {
			addCriterion("PRODUCER <>", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerGreaterThan(String value) {
			addCriterion("PRODUCER >", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCER >=", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLessThan(String value) {
			addCriterion("PRODUCER <", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLessThanOrEqualTo(String value) {
			addCriterion("PRODUCER <=", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerLike(String value) {
			addCriterion("PRODUCER like", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotLike(String value) {
			addCriterion("PRODUCER not like", value, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerIn(List<String> values) {
			addCriterion("PRODUCER in", values, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotIn(List<String> values) {
			addCriterion("PRODUCER not in", values, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerBetween(String value1, String value2) {
			addCriterion("PRODUCER between", value1, value2, "producer");
			return (Criteria) this;
		}

		public Criteria andProducerNotBetween(String value1, String value2) {
			addCriterion("PRODUCER not between", value1, value2, "producer");
			return (Criteria) this;
		}

		public Criteria andUniIdIsNull() {
			addCriterion("UNI_ID is null");
			return (Criteria) this;
		}

		public Criteria andUniIdIsNotNull() {
			addCriterion("UNI_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUniIdEqualTo(String value) {
			addCriterion("UNI_ID =", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdNotEqualTo(String value) {
			addCriterion("UNI_ID <>", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdGreaterThan(String value) {
			addCriterion("UNI_ID >", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdGreaterThanOrEqualTo(String value) {
			addCriterion("UNI_ID >=", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdLessThan(String value) {
			addCriterion("UNI_ID <", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdLessThanOrEqualTo(String value) {
			addCriterion("UNI_ID <=", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdLike(String value) {
			addCriterion("UNI_ID like", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdNotLike(String value) {
			addCriterion("UNI_ID not like", value, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdIn(List<String> values) {
			addCriterion("UNI_ID in", values, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdNotIn(List<String> values) {
			addCriterion("UNI_ID not in", values, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdBetween(String value1, String value2) {
			addCriterion("UNI_ID between", value1, value2, "uniId");
			return (Criteria) this;
		}

		public Criteria andUniIdNotBetween(String value1, String value2) {
			addCriterion("UNI_ID not between", value1, value2, "uniId");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andImageUrlIsNull() {
			addCriterion("IMAGE_URL is null");
			return (Criteria) this;
		}

		public Criteria andImageUrlIsNotNull() {
			addCriterion("IMAGE_URL is not null");
			return (Criteria) this;
		}

		public Criteria andImageUrlEqualTo(String value) {
			addCriterion("IMAGE_URL =", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotEqualTo(String value) {
			addCriterion("IMAGE_URL <>", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlGreaterThan(String value) {
			addCriterion("IMAGE_URL >", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
			addCriterion("IMAGE_URL >=", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLessThan(String value) {
			addCriterion("IMAGE_URL <", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLessThanOrEqualTo(String value) {
			addCriterion("IMAGE_URL <=", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLike(String value) {
			addCriterion("IMAGE_URL like", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotLike(String value) {
			addCriterion("IMAGE_URL not like", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlIn(List<String> values) {
			addCriterion("IMAGE_URL in", values, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotIn(List<String> values) {
			addCriterion("IMAGE_URL not in", values, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlBetween(String value1, String value2) {
			addCriterion("IMAGE_URL between", value1, value2, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotBetween(String value1, String value2) {
			addCriterion("IMAGE_URL not between", value1, value2, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andChannelIsNull() {
			addCriterion("CHANNEL is null");
			return (Criteria) this;
		}

		public Criteria andChannelIsNotNull() {
			addCriterion("CHANNEL is not null");
			return (Criteria) this;
		}

		public Criteria andChannelEqualTo(String value) {
			addCriterion("CHANNEL =", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotEqualTo(String value) {
			addCriterion("CHANNEL <>", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThan(String value) {
			addCriterion("CHANNEL >", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThanOrEqualTo(String value) {
			addCriterion("CHANNEL >=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThan(String value) {
			addCriterion("CHANNEL <", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThanOrEqualTo(String value) {
			addCriterion("CHANNEL <=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLike(String value) {
			addCriterion("CHANNEL like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotLike(String value) {
			addCriterion("CHANNEL not like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelIn(List<String> values) {
			addCriterion("CHANNEL in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotIn(List<String> values) {
			addCriterion("CHANNEL not in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelBetween(String value1, String value2) {
			addCriterion("CHANNEL between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotBetween(String value1, String value2) {
			addCriterion("CHANNEL not between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNull() {
			addCriterion("CATEGORY is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNotNull() {
			addCriterion("CATEGORY is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryEqualTo(String value) {
			addCriterion("CATEGORY =", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotEqualTo(String value) {
			addCriterion("CATEGORY <>", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThan(String value) {
			addCriterion("CATEGORY >", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("CATEGORY >=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThan(String value) {
			addCriterion("CATEGORY <", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThanOrEqualTo(String value) {
			addCriterion("CATEGORY <=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLike(String value) {
			addCriterion("CATEGORY like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotLike(String value) {
			addCriterion("CATEGORY not like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryIn(List<String> values) {
			addCriterion("CATEGORY in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotIn(List<String> values) {
			addCriterion("CATEGORY not in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryBetween(String value1, String value2) {
			addCriterion("CATEGORY between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotBetween(String value1, String value2) {
			addCriterion("CATEGORY not between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andPublishDateIsNull() {
			addCriterion("PUBLISH_DATE is null");
			return (Criteria) this;
		}

		public Criteria andPublishDateIsNotNull() {
			addCriterion("PUBLISH_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andPublishDateEqualTo(Date value) {
			addCriterionForJDBCDate("PUBLISH_DATE =", value, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("PUBLISH_DATE <>", value, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateGreaterThan(Date value) {
			addCriterionForJDBCDate("PUBLISH_DATE >", value, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PUBLISH_DATE >=", value, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateLessThan(Date value) {
			addCriterionForJDBCDate("PUBLISH_DATE <", value, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PUBLISH_DATE <=", value, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateIn(List<Date> values) {
			addCriterionForJDBCDate("PUBLISH_DATE in", values, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("PUBLISH_DATE not in", values, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PUBLISH_DATE between", value1, value2, "publishDate");
			return (Criteria) this;
		}

		public Criteria andPublishDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PUBLISH_DATE not between", value1, value2, "publishDate");
			return (Criteria) this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("MEMO is null");
			return (Criteria) this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("MEMO is not null");
			return (Criteria) this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("MEMO =", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("MEMO <>", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("MEMO >", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("MEMO >=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("MEMO <", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("MEMO <=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("MEMO like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("MEMO not like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoIn(List<String> values) {
			addCriterion("MEMO in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotIn(List<String> values) {
			addCriterion("MEMO not in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("MEMO between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("MEMO not between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andDurationIsNull() {
			addCriterion("DURATION is null");
			return (Criteria) this;
		}

		public Criteria andDurationIsNotNull() {
			addCriterion("DURATION is not null");
			return (Criteria) this;
		}

		public Criteria andDurationEqualTo(Date value) {
			addCriterion("DURATION =", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotEqualTo(Date value) {
			addCriterion("DURATION <>", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThan(Date value) {
			addCriterion("DURATION >", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThanOrEqualTo(Date value) {
			addCriterion("DURATION >=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThan(Date value) {
			addCriterion("DURATION <", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThanOrEqualTo(Date value) {
			addCriterion("DURATION <=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationIn(List<Date> values) {
			addCriterion("DURATION in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotIn(List<Date> values) {
			addCriterion("DURATION not in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationBetween(Date value1, Date value2) {
			addCriterion("DURATION between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotBetween(Date value1, Date value2) {
			addCriterion("DURATION not between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andDetailedIsNull() {
			addCriterion("DETAILED is null");
			return (Criteria) this;
		}

		public Criteria andDetailedIsNotNull() {
			addCriterion("DETAILED is not null");
			return (Criteria) this;
		}

		public Criteria andDetailedEqualTo(Boolean value) {
			addCriterion("DETAILED =", value, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedNotEqualTo(Boolean value) {
			addCriterion("DETAILED <>", value, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedGreaterThan(Boolean value) {
			addCriterion("DETAILED >", value, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("DETAILED >=", value, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedLessThan(Boolean value) {
			addCriterion("DETAILED <", value, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedLessThanOrEqualTo(Boolean value) {
			addCriterion("DETAILED <=", value, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedIn(List<Boolean> values) {
			addCriterion("DETAILED in", values, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedNotIn(List<Boolean> values) {
			addCriterion("DETAILED not in", values, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedBetween(Boolean value1, Boolean value2) {
			addCriterion("DETAILED between", value1, value2, "detailed");
			return (Criteria) this;
		}

		public Criteria andDetailedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("DETAILED not between", value1, value2, "detailed");
			return (Criteria) this;
		}

		public Criteria andAlbumCountIsNull() {
			addCriterion("ALBUM_COUNT is null");
			return (Criteria) this;
		}

		public Criteria andAlbumCountIsNotNull() {
			addCriterion("ALBUM_COUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAlbumCountEqualTo(Integer value) {
			addCriterion("ALBUM_COUNT =", value, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountNotEqualTo(Integer value) {
			addCriterion("ALBUM_COUNT <>", value, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountGreaterThan(Integer value) {
			addCriterion("ALBUM_COUNT >", value, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("ALBUM_COUNT >=", value, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountLessThan(Integer value) {
			addCriterion("ALBUM_COUNT <", value, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountLessThanOrEqualTo(Integer value) {
			addCriterion("ALBUM_COUNT <=", value, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountIn(List<Integer> values) {
			addCriterion("ALBUM_COUNT in", values, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountNotIn(List<Integer> values) {
			addCriterion("ALBUM_COUNT not in", values, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountBetween(Integer value1, Integer value2) {
			addCriterion("ALBUM_COUNT between", value1, value2, "albumCount");
			return (Criteria) this;
		}

		public Criteria andAlbumCountNotBetween(Integer value1, Integer value2) {
			addCriterion("ALBUM_COUNT not between", value1, value2, "albumCount");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("SCORE is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("SCORE is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Integer value) {
			addCriterion("SCORE =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Integer value) {
			addCriterion("SCORE <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Integer value) {
			addCriterion("SCORE >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("SCORE >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Integer value) {
			addCriterion("SCORE <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Integer value) {
			addCriterion("SCORE <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Integer> values) {
			addCriterion("SCORE in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Integer> values) {
			addCriterion("SCORE not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Integer value1, Integer value2) {
			addCriterion("SCORE between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("SCORE not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("STATE is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("STATE is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("STATE =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("STATE <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("STATE >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATE >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("STATE <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("STATE <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("STATE in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("STATE not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("STATE between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("STATE not between", value1, value2, "state");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table MOVIE
	 * 
	 * @mbg.generated Fri Sep 24 16:39:24 JST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table MOVIE
	 *
	 * @mbg.generated do_not_delete_during_merge Tue Aug 31 10:14:26 JST 2021
	 */
	public static class Criteria extends GeneratedCriteria {
		protected Criteria() {
			super();
		}
	}

	private int start;

	private int count;

	/**
	 * @return the start
	 */
	public int getStart() {
		return this.start;
	}

	/**
	 * @param start the start to set
	 */
	public void setStart(int start) {
		this.start = start;
	}

	/**
	 * @return the count
	 */
	public int getCount() {
		return this.count;
	}

	/**
	 * @param count the count to set
	 */
	public void setCount(int count) {
		this.count = count;
	}

}