package org.aquarius.cicada.core.model;

import java.io.Serializable;
import java.util.Date;

public class VisitHistory implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.ID
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.SITE_NAME
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private String siteName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.LAST_VISIT_PAGE_NUMBER
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private Integer lastVisitPageNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.LAST_TOTAL_PAGE_COUNT
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private Integer lastTotalPageCount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.LAST_UPDATE
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private Date lastUpdate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.LAST_PAGE_URLS
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private String lastPageUrls;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.CHANNEL
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private String channel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column VISIT_HISTORY.FINISHED
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private Boolean finished;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	private static final long serialVersionUID = 1L;

	private boolean hasError = false;

	/**
	 * @return the hasError
	 */
	public boolean isHasError() {
		return this.hasError;
	}

	/**
	 * @param hasError the hasError to set
	 */
	public void setHasError(boolean hasError) {
		this.hasError = hasError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.ID
	 *
	 * @return the value of VISIT_HISTORY.ID
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.ID
	 *
	 * @param id the value for VISIT_HISTORY.ID
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.SITE_NAME
	 *
	 * @return the value of VISIT_HISTORY.SITE_NAME
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public String getSiteName() {
		return this.siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.SITE_NAME
	 *
	 * @param siteName the value for VISIT_HISTORY.SITE_NAME
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.LAST_VISIT_PAGE_NUMBER
	 *
	 * @return the value of VISIT_HISTORY.LAST_VISIT_PAGE_NUMBER
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public Integer getLastVisitPageNumber() {
		return this.lastVisitPageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.LAST_VISIT_PAGE_NUMBER
	 *
	 * @param lastVisitPageNumber the value for VISIT_HISTORY.LAST_VISIT_PAGE_NUMBER
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setLastVisitPageNumber(Integer lastVisitPageNumber) {
		this.lastVisitPageNumber = lastVisitPageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.LAST_TOTAL_PAGE_COUNT
	 *
	 * @return the value of VISIT_HISTORY.LAST_TOTAL_PAGE_COUNT
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public Integer getLastTotalPageCount() {
		return this.lastTotalPageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.LAST_TOTAL_PAGE_COUNT
	 *
	 * @param lastTotalPageCount the value for VISIT_HISTORY.LAST_TOTAL_PAGE_COUNT
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setLastTotalPageCount(Integer lastTotalPageCount) {
		this.lastTotalPageCount = lastTotalPageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.LAST_UPDATE
	 *
	 * @return the value of VISIT_HISTORY.LAST_UPDATE
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.LAST_UPDATE
	 *
	 * @param lastUpdate the value for VISIT_HISTORY.LAST_UPDATE
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.LAST_PAGE_URLS
	 *
	 * @return the value of VISIT_HISTORY.LAST_PAGE_URLS
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public String getLastPageUrls() {
		return this.lastPageUrls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.LAST_PAGE_URLS
	 *
	 * @param lastPageUrls the value for VISIT_HISTORY.LAST_PAGE_URLS
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setLastPageUrls(String lastPageUrls) {
		this.lastPageUrls = lastPageUrls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.CHANNEL
	 *
	 * @return the value of VISIT_HISTORY.CHANNEL
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public String getChannel() {
		return this.channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.CHANNEL
	 *
	 * @param channel the value for VISIT_HISTORY.CHANNEL
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column VISIT_HISTORY.FINISHED
	 *
	 * @return the value of VISIT_HISTORY.FINISHED
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public Boolean getFinished() {
		return this.finished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column VISIT_HISTORY.FINISHED
	 *
	 * @param finished the value for VISIT_HISTORY.FINISHED
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	public void setFinished(Boolean finished) {
		this.finished = finished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		VisitHistory other = (VisitHistory) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getSiteName() == null ? other.getSiteName() == null : this.getSiteName().equals(other.getSiteName()))
				&& (this.getLastVisitPageNumber() == null ? other.getLastVisitPageNumber() == null
						: this.getLastVisitPageNumber().equals(other.getLastVisitPageNumber()))
				&& (this.getLastTotalPageCount() == null ? other.getLastTotalPageCount() == null
						: this.getLastTotalPageCount().equals(other.getLastTotalPageCount()))
				&& (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()))
				&& (this.getLastPageUrls() == null ? other.getLastPageUrls() == null : this.getLastPageUrls().equals(other.getLastPageUrls()))
				&& (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
				&& (this.getFinished() == null ? other.getFinished() == null : this.getFinished().equals(other.getFinished()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getSiteName() == null) ? 0 : getSiteName().hashCode());
		result = prime * result + ((getLastVisitPageNumber() == null) ? 0 : getLastVisitPageNumber().hashCode());
		result = prime * result + ((getLastTotalPageCount() == null) ? 0 : getLastTotalPageCount().hashCode());
		result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
		result = prime * result + ((getLastPageUrls() == null) ? 0 : getLastPageUrls().hashCode());
		result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
		result = prime * result + ((getFinished() == null) ? 0 : getFinished().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(this.id);
		sb.append(", siteName=").append(this.siteName);
		sb.append(", lastVisitPageNumber=").append(this.lastVisitPageNumber);
		sb.append(", lastTotalPageCount=").append(this.lastTotalPageCount);
		sb.append(", lastUpdate=").append(this.lastUpdate);
		sb.append(", lastPageUrls=").append(this.lastPageUrls);
		sb.append(", channel=").append(this.channel);
		sb.append(", finished=").append(this.finished);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}