package org.aquarius.cicada.core.model;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface VisitHistoryMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	long countByExample(VisitHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int deleteByExample(VisitHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int insert(VisitHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int insertSelective(VisitHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	List<VisitHistory> selectByExample(VisitHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	VisitHistory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int updateByExampleSelective(@Param("record") VisitHistory record, @Param("example") VisitHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int updateByExample(@Param("record") VisitHistory record, @Param("example") VisitHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int updateByPrimaryKeySelective(VisitHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table VISIT_HISTORY
	 *
	 * @mbg.generated Sat Sep 25 10:34:13 JST 2021
	 */
	int updateByPrimaryKey(VisitHistory record);
}